In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/icail

/content/drive/MyDrive/icail

In [3]:
%run coliee25/models/rerank/crossencoder.py

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
%run retrieval/dense/bge/bge_final.py

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Encoding all articles...

Batches:   0%|          | 0/24 [00:00<?, ?it/s]

Building MarginMSE triplets...
Total MarginMSE samples: 10736
['Represent this sentence for searching relevant passages: If A holds a monitory claim against B, and B holds a monitory claim against C, A may not exercise the claim of B against C beyond the amount of A’s claim, based on the obligee’s right of subrogation to preserve the claim of A against B.', "If the obligee exercises the subrogor's right, and the subject matter of the subrogor's right is divisible, the obligee may exercise the subrogor's right only to the extent of the amount of the obligee's own claim.", 'Beyond the cases referred to in the preceding Article, partners withdraw on the following grounds: (i) the partner dies; (ii) the partner is subject to an order commencing bankruptcy proceeding; (iii) the partner is subject to a decision for the commencement of guardianship; (iv) the partner has been expelled.']

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
%run retrieval/dense/bge/en_bge.py

/content/drive/MyDrive/icail/retrieval/dense/bge/en_bge.py:16: DeprecationWarning: Importing from 'sentence_transformers.losses' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.losses' instead.
  from sentence_transformers import SentenceTransformer, losses
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

42

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
%run retrieval/dense/bge/infer.py

Loading model: ./coliee25/outputs/runs/bge-triplet-final/model

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Loading queries...
Loading articles...
Encoding articles...
Encoding queries...
Retrieving...

In [ ]:
%run metrics/metric.py

Top-  1 | P=0.3014 R=0.2740 F2=0.2770
Top-  2 | P=0.1986 R=0.3470 F2=0.2971
Top-  3 | P=0.1689 R=0.4566 F2=0.3355
Top-  4 | P=0.1336 R=0.4840 F2=0.3125
Top-  5 | P=0.1096 R=0.4977 F2=0.2868
Top-  6 | P=0.0913 R=0.4977 F2=0.2592
Top-  7 | P=0.0822 R=0.5114 F2=0.2456
Top-  8 | P=0.0771 R=0.5388 F2=0.2403
Top-  9 | P=0.0715 R=0.5594 F2=0.2320
Top- 10 | P=0.0644 R=0.5594 F2=0.2162
Top- 20 | P=0.0390 R=0.6758 F2=0.1563
Top- 50 | P=0.0178 R=0.7489 F2=0.0805
Top-100 | P=0.0096 R=0.7968 F2=0.0455
Top-200 | P=0.0057 R=0.9178 F2=0.0276
Top-500 | P=0.0024 R=0.9658 F2=0.0121